## numpy array and basics
learn about numpy

In [2]:
import numpy as np

# creating array from list


In [4]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)


1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


# list vs numpy array

In [7]:
py_list = [1,2,3]
print("Python list multiplication ", py_list*2)

np_array = np.array([1,2,3]) # element wise multiplication
print("Python array multiplication ", np_array * 2)
 




import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:", time.time() - start)


start = time.time()
np_array = np.arange(100000)
print("\n Numpy operation time:", time.time() - start)


Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time: 0.13292479515075684

 Numpy operation time: 0.0010309219360351562


# creating array from scratch

In [14]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)



ones = np.ones((2,3))
print("ones array: \n", ones)


full = np.full((2,3),5)
print("full array: \n", full)



random = np.random.random((2,3))
print("random array: \n", random)


sequence = np.arange(0,10,2)
print("sequence array: \n", sequence)



zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[5 5 5]
 [5 5 5]]
random array: 
 [[0.1033328  0.67962981 0.91895918]
 [0.23263179 0.89155634 0.27043122]]
sequence array: 
 [0 2 4 6 8]


# vector, matrix and tensor

In [19]:
vector = np.array([1,2,3])
print("vector", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor", tensor)

vector [1 2 3]
matrix [[1 2 3]
 [4 5 6]]
tensor [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# array properties:

In [3]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("Data Type ", arr.dtype)

shape  (2, 3)
Dimension  2
Size  6
Data Type  int64


# array Reshaping

In [11]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("\n Reshape arry ", reshaped)

# copy return krta hai, original ravel() return krta hai
flattened = reshaped.flatten()
print("\n Flattened array", flattened)

# ravel (returns views, insted of copy)
reveled = reshaped.ravel()
print("\n Ravled array", reveled)


Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshape arry  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Ravled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


# transpose of matrix

In [12]:
transpose = reshaped.T
print("\n Transpose array ", transpose)


 Transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
