# Numpy array operations

In [17]:
import numpy as np

indexing 

In [18]:
arr = np.array([1,2,3,4,5,7,8])
print("Basic Slicing", arr[0:8])
print("With Step", arr[1:8:2]) # step of 2
print("Negative  indexing", arr[-3])


Basic Slicing [1 2 3 4 5 7 8]
With Step [2 4 7]
Negative  indexing 5


indexing on 2D

In [19]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element", arr_2d[1,2]) # here 1 is the 2nd(beacuse indexing start from 0) row
                                          # and 2 is the 3rd element of that row

print("Entire row: ", arr_2d[1]) # give me the entire second row
print("Entire col: ", arr_2d[:,1]) # give me the second column



Specific element 6
Entire row:  [4 5 6]
Entire col:  [2 5 8]


# sorting

In [20]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted Array ", np.sort(unsorted))



arr_2d_unsorted =  np.array([[3,1], [1,2], [3,2]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=1))
# jab axis=0 rhta hai tab, hm pure array me se sort krte hai jaise [1,1], [2,2], [3,3]
# lekin jab axis=1 rhta hai tab particular block of element ko arange krte hai jaise [1,3],[1,2],[2,3]


Sorted Array  [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 3]
 [1 2]
 [2 3]]


# filter

In [21]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = number[number % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


# Filter with mask

In [22]:
mask = number > 5
print("Numbers grater than 5 ", number[mask])

Numbers grater than 5  [ 6  7  8  9 10]


# fancy indexing vs np.where()

In [23]:
indices = [0,2,4]
print(number[indices])


where_result = np.where(number > 5)
print(where_result)
print("NP where", number[where_result])


[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [24]:
condition_array = np.where(number > 5, number*3, number) 
print(condition_array)

# # it is same as:
# if(number>5) {
#     number *3
# }
# else {
#     number
# }

[ 1  2  3  4  5 18 21 24 27 30]


# Adding and Removing Data

In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# combined = arr1 + arr2
# print(combined)

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


# array compatibility

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

print("Compatibility shapes", a.shape == b.shape)
print("Compatibility shapes", a.shape == c.shape)

Compatibility shapes True
Compatibility shapes False


In [32]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
# print(with_new_row) # vstack always addd row and left to right is row

print(original)
print(with_new_row)



new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col)) # hstack always add column
print("with new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new column [[1 2 7]
 [3 4 8]]


deleting

In [40]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,1)
print("Array after deletion: ", deleted)

Array after deletion:  [1 3 4 5]
